### ISSUE TITLE
syntax error activating as a plugin?

### ISSUE THREAD

**Issue by tmuka** [timbofield/wordpress-dispatcher#1]
Hi, thanks for sharing this code. Were you able to use it as a plugin?  I'm getting an error trying to activate the plugin.  I'm using a LAMP server with php 5.3.2.

Parse error: syntax error, unexpected '[' in /var/www/vhosts/example.com/httpdocs/wp-content/plugins/wordpress-dispatcher/Dispatch.php on line 13

Thanks!

**Comment by tmuka** [comment]
Ah, yeah, it looks like i had to switch the php 5.4 array syntax to 5.3 compatible for my server.

$newRule = array('^'.trim($look_for_in_url,'/').'/?$' => 'index.php?'.$this->query_var_name($look_for_in_url).'=1');

**Comment by tmuka** [comment]
It looks like there are a few other syntax changes that wont work in php 5.3. understandable, but probably worth noting in the readme :)  thanks!

**Comment by tim-field** [comment]
Yeah sorry you'll need >= 5.4, composer should let you know this if you install it that way.

https://github.com/timbofield/wordpress-dispatcher/blob/master/composer.json#L12

**Comment by tmuka** [comment]
thanks :)
