### ISSUE TITLE
class name in Router.php at version 2.0 seems wrong

### ISSUE THREAD

**Issue by waniks** [timbofield/wordpress-dispatcher#3]
the class name is still Dispatch, and autoload can't find this file correctly.

**Comment by tim-field** [comment]
Hmm not sure what you mean, can you link to the source code please.

**Comment by waniks** [comment]
https://github.com/tim-field/wordpress-dispatcher/blob/2.0/Router.php#L5
At tag 2.0, the file name is Router.php but class name is Dispatch.
This leads to fatal error whether i use TheFold\WordPress\Router or TheFold\WordPress\Dispatch

**Comment by tim-field** [comment]
Thanks have fixed with a 2.1 tag now
